### ISSUE TITLE
Demo is failing: Service is connected to repository with newer schema (58)

### ISSUE THREAD

**Issue by LRomano72** [2sky/Vidyano#110]
### Description
Service is connected to repository with newer schema (58)

#### Steps to Reproduce
1. Click this link: https://demo.vidyano.com/
2. …
3. …

#### Expected Results
Demo should work.

#### Actual Results
https://demo.vidyano.com/

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Vidyano: vX.X.X.X
- Vidyano Web²: vX.X.X-prerelease-hash (use ```Vidyano.version```)

**Comment by stevehansen** [comment]
Fixed, thanks for reporting, the continuous deployment wasn't working as expected.
