### ISSUE TITLE
Documentation on how to create a relationship and a dropdown list from another query?

### ISSUE THREAD

**Issue by ravensorb** [2sky/Vidyano#117]
I am extremely impressed with Vidyano so far -- just one question, is there any information, documentation or video on how to create a relationship with another entity so that I use it in a picklist/dropdown?

**Comment by wimr** [comment]
Hey,

I'm assuming the following: 

1. You have your relation setup correctly in your entity framework model 
2. You used Synchronize, to update your persistent objects with you your entity framework model 
![image](https://user-images.githubusercontent.com/610620/41833722-cf262e3c-7851-11e8-90e5-4f8287a7f5c6.png)

You can now navigate to the "persistent object attribute with reference" (the attribute with the name of your collection property on your model)
Here you can edit a lot of stuff about the reference including: 

1. Select in-place: change the reference from a query view to a dropdown
2. Change the actual query that will be used (your lookup query) [beware that the PersistentObject of the query stays the same]
3. Specify if you want your users to be able to create a new reference value starting from the edit screen you are on. 

If you haven't created a custom query yet, you can look inside the [schemaname]Queries.cs for a reference signature. don't forget to add the query defenition to the queries in the management part to start using it.

**Comment by ravensorb** [comment]
Thanks!  Only issue now is, I added an entity to the menu and "boom" now all I get is a white screen in the browser.  Any suggestions on how to troubleshoot?

**Comment by wimr** [comment]
Hey, sounds like your webserver (iis express?) is not responding to your requests. You can always check chrome's developer tools or attach your debugger to the process
