### ISSUE TITLE
Sample with ASP user, Role and Groups

### ISSUE THREAD

**Issue by weedkiller** [2sky/Vidyano#125]
Hi, can you please add a sample web app, that could be cloud ready like ABP or Serenity, that has user, role and group management baked in with permissions.

thanks

**Comment by Sleeckx** [comment]
Hi, you can find more information on the [website ](https://vidyano.com/learn). Role and user/group management is handled in the application under Management ˃ Security. More information can be found [here](http://old.vidyano.com/#!/Documentation/security?Web).
