### ISSUE TITLE
Using YesNo/Boolean/NullableBoolean with TrueKey/FalseKey still renders checkboxes in grid

### ISSUE THREAD

**Issue by stevehansen** [2sky/Vidyano#99]
![image](https://cloud.githubusercontent.com/assets/2143488/26685570/d04b6104-46ea-11e7-81d1-bd947ad58da6.png)

**Comment by Sleeckx** [comment]
Fixed in 9d38630e8f9b585c84c00b23935c6a25d367b2ba
